/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as EmailVerificationRequiredRouteImport } from './routes/email-verification-required'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as RequestNewRouteImport } from './routes/request.new'
import { Route as PhotoRequestIdRouteImport } from './routes/photo.$requestId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerificationRequiredRoute =
  EmailVerificationRequiredRouteImport.update({
    id: '/email-verification-required',
    path: '/email-verification-required',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNewRoute = RequestNewRouteImport.update({
  id: '/request/new',
  path: '/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRequestIdRoute = PhotoRequestIdRouteImport.update({
  id: '/photo/$requestId',
  path: '/photo/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/photo/$requestId': typeof PhotoRequestIdRoute
  '/request/new': typeof RequestNewRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/photo/$requestId': typeof PhotoRequestIdRoute
  '/request/new': typeof RequestNewRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/email-verification-required': typeof EmailVerificationRequiredRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/photo/$requestId': typeof PhotoRequestIdRoute
  '/request/new': typeof RequestNewRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/email-verification-required'
    | '/signin'
    | '/signup'
    | '/photo/$requestId'
    | '/request/new'
    | '/verify-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/email-verification-required'
    | '/signin'
    | '/signup'
    | '/photo/$requestId'
    | '/request/new'
    | '/verify-email/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/email-verification-required'
    | '/signin'
    | '/signup'
    | '/photo/$requestId'
    | '/request/new'
    | '/verify-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EmailVerificationRequiredRoute: typeof EmailVerificationRequiredRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  PhotoRequestIdRoute: typeof PhotoRequestIdRoute
  RequestNewRoute: typeof RequestNewRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verification-required': {
      id: '/email-verification-required'
      path: '/email-verification-required'
      fullPath: '/email-verification-required'
      preLoaderRoute: typeof EmailVerificationRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/new': {
      id: '/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof RequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$requestId': {
      id: '/photo/$requestId'
      path: '/photo/$requestId'
      fullPath: '/photo/$requestId'
      preLoaderRoute: typeof PhotoRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EmailVerificationRequiredRoute: EmailVerificationRequiredRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  PhotoRequestIdRoute: PhotoRequestIdRoute,
  RequestNewRoute: RequestNewRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
